### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by longseespace** [longseespace/qix#1]
### Chores
- [x] Move `qml-renderer` to a separated package
- [x] Move `qml-loader` to bundler package
- [ ] Test

### Features
- [x] Convert QtQuick components
- [ ] Make TextField, TextInput controllable
- [ ] Implement CLI
  - [ ] init (generate `App.pro` + install js dependencies)
  - [x] bundle (build js bundle for offline use)
  - [x] start (dev server)
  - [ ] run (build `App.pro` + exec binary)
- [x] Resource handling

### Fixes
- [x] QML doesn't allow modifying `Error.name`
